//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int HallId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long CellNumber { get; set; }
        public long NICNumber { get; set; }
        public string EmailAddress { get; set; }
        public string BookingPurpose { get; set; }
        public decimal Price { get; set; }
        public int NumberofGuest { get; set; }
        public DateTime DateofOccasion { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
