using Website.Models;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    using Website.Models;

    public partial class Hall
    {
        public Hall()
        {
            this.Bookings = new HashSet<Booking>();
            this.Imagess = new HashSet<Images>();
            this.Videoss = new HashSet<Videos>();
        }

        public int HallId { get; set; }
        public int VenueId { get; set; }
        
        public string Name { get; set; }
        public decimal Price { get; set; }
        public long Numberofperson { get; set; }

        public virtual ICollection<HallType> HallTypes { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual ICollection<Images> Imagess { get; set; }
        public virtual ICollection<Videos> Videoss { get; set; }
    }
}
