//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Images
    {
        public int ImagesId { get; set; }
        public int HallId { get; set; }
        public string Image { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
